name: SimpleMessage
main: com.brageast.main
version: 1.1

softdepend: [PlaceholderAPI]

commands:
  smsg:
    description: "主要指令"
    usgae: /<command>
permission:
  simplemessage.use:
    default: false