name: SimpleMessages
main: com.brageast.main
version: 1.1

softdepend: [PlaceholderAPI]

commands:
  smsg:
    description: "主要指令"
    usgae: /<command>
  smt:
    description: "主要指令"
    usgae: /<command>
permission:
  simplemessage.use:
    default: true
  simplemessage.use.tpa:
    default: true